login:
  path:     /get-apikey
  defaults: { _controller: AccessBundle:Auth:getApiKey}
  requirements:
    _method: POST

register:
  path:     /register
  defaults: { _controller: AccessBundle:Auth:register }
  requirements:
    _method: PUT


forgot:
  path:     /forgot
  defaults: { _controller: AccessBundle:Auth:forgot }

forgotMail:
  path:     /forgot_mail
  defaults: { _controller: AccessBundle:Auth:showForgotMail }
