login:
    path:     /login
    defaults: { _controller: AccessBundle:Auth:login}
    requirements:
        _method: POST

register:
    path:     /register
    defaults: { _controller: AccessBundle:Auth:register }

forgot:
    path:     /forgot
    defaults: { _controller: AccessBundle:Auth:forgot }