<?php

namespace AccessBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ApiBundle\Interfaces\ApiKeyHandlerInterface;
/**
 * ApiKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiKeyRepository extends EntityRepository implements ApiKeyHandlerInterface
{
    public function getUsernameFromApiKey($apiKey) {
        $result = $this->findOneBy(array('apiKey' => $apiKey, 'isActive'=> false));
        var_dump($result); exit;
    }
}
