<?php

namespace AccessBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ApiBundle\Interfaces\ApiKeyHandlerInterface;
use AccessBundle\Entity\ApiKey;
use ApiBundle\Entity\User;


/**
 * ApiKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiKeyRepository extends EntityRepository implements ApiKeyHandlerInterface
{
    public function getUsernameFromApiKey($apiKey)
    {
        $username = null;
        try {
            /**
             * @var \AccessBundle\Entity\ApiKey
             */
            $result = $this->findOneBy(array('apiKey' => $apiKey));

            if ($result instanceof ApiKey and $result->getUser() instanceof User) {
                $username = $result->getUser()->getUsername();
            }
        } catch (Exception $e) {
            $username = null;
        }
        return $username;
    }
}
