<?php

namespace AccessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApiKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiKeyRepository extends EntityRepository
{
}
