# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
   user_entity: ApiBundle\Entity\User
   user_repository: ApiBundle\Entity\UserRepository
   
   apiKey_entity: AccessBundle\Entity\ApiKey
   apiKey_repository: AccessBundle\Entity\ApiKeyRepository


services:
    users_handler:
        class: %user_repository%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - %user_entity%
    apiKey_handler:
        class: %apiKey_repository%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - %apiKey_entity%

    apikey_authenticator:
        class:  AccessBundle\Security\ApiKeyAuthenticator
        public: false

    api_key_user_provider:
        class: AccessBundle\Security\ApiKeyUserProvider
        arguments: ["@users_handler", "@apiKey_handler"]


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
