_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt
    schemes: ['https']

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler
    schemes: ['https']

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator
    schemes: ['https']

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error
    schemes: ['https']

_main:
    resource: routing.yml
    schemes: ['https']