users_me:
    pattern:  /me.{_format}
    defaults: { _controller: ApiBundle:Default:getMe, _format: json }
    requirements:
        _method: GET
users_get:
    pattern:  /{username}.{_format}
    defaults: { _controller: ApiBundle:Default:get, _format: json }
    requirements:
        _method: GET

    
