me:
    pattern:  /me
    defaults: { _controller: ApiBundle:User:getMe }
    requirements:
        _method: GET
get:
    pattern:  /{username}
    defaults: { _controller: ApiBundle:User:get }
    requirements:
        _method: GET