me:
    pattern:  /me
    defaults: { _controller: ApiBundle:User:getMe }
    requirements:
        _method: GET
get:
    pattern:  /{id}
    defaults: { _controller: ApiBundle:User:get }
    requirements:
        id: "\d+"
        _method: GET